---
services:
  itenergy-service:
    build: .
    container_name: itenergy
    depends_on:
      - itenergy-service-postgres
    volumes:
      - ${PWD}:/app
    environment:
      - VIRTUAL_HOST=itenergy.docker
    command: ["uvicorn", "itenergy.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8000:8000

  itenergy-service-postgres:
    container_name: itenergy-service-postgres
    image: postgres:14.2
    environment:
      PGHOST: itenergy-service-postgres
      PGPORT: 5432
      POSTGRES_DB: itenergy
      POSTGRES_USER: itenergy
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

#  http-proxy:
#    container_name: http-proxy
#    image: codekitchen/dinghy-http-proxy
#    environment:
#      - DNS_IP=127.0.0.1
#      - CONTAINER_NAME=http-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#      - "19322:19322/udp"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
