"""Add weather_forecast table

Revision ID: 350a7d6bf972
Revises:
Create Date: 2023-11-20 22:00:46.419524

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '350a7d6bf972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_switch',
                    sa.Column('forecast_id', sa.Integer(), nullable=False),
                    sa.Column('v1_state', sa.Integer(), nullable=False),
                    sa.Column('v2_state', sa.Integer(), nullable=False),
                    sa.Column('v3_state', sa.Integer(), nullable=False),
                    sa.Column('v4_state', sa.Integer(), nullable=False),
                    sa.Column('v5_state', sa.Integer(), nullable=False),
                    sa.Column('v6_state', sa.Integer(), nullable=False),
                    sa.Column('v7_state', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('forecast_id')
                    )
    op.create_index(op.f('ix_forecast_switch_forecast_id'), 'forecast_switch', ['forecast_id'],
                    unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_switch_forecast_id'), table_name='forecast_switch')
    op.drop_table('forecast_switch')
    # ### end Alembic commands ###
