"""Add all fields to equipment table

Revision ID: 602147c8dff9
Revises: 0aac60b54a54
Create Date: 2023-12-11 21:31:33.748053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '602147c8dff9'
down_revision = '0aac60b54a54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('voltage_deviation', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('phase_voltage_ua', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('phase_voltage_ub', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('phase_voltage_uc', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('interphase_voltage_uab', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('interphase_voltage_uac', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('interphase_voltage_ubc', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('asymmetry_coefficient_k2u', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('asymmetry_coefficient_k0u', sa.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('capacity_battery_pb', sa.FLOAT(), nullable=True))
    op.alter_column('equipment', 'current_solar_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'current_wind_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'solar_battery_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'wind_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'power_consumption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'power_consumption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('equipment', 'wind_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('equipment', 'solar_battery_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('equipment', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('equipment', 'current_wind_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('equipment', 'current_solar_power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('equipment', 'capacity_battery_pb')
    op.drop_column('equipment', 'asymmetry_coefficient_k0u')
    op.drop_column('equipment', 'asymmetry_coefficient_k2u')
    op.drop_column('equipment', 'interphase_voltage_ubc')
    op.drop_column('equipment', 'interphase_voltage_uac')
    op.drop_column('equipment', 'interphase_voltage_uab')
    op.drop_column('equipment', 'phase_voltage_uc')
    op.drop_column('equipment', 'phase_voltage_ub')
    op.drop_column('equipment', 'phase_voltage_ua')
    op.drop_column('equipment', 'voltage_deviation')
    # ### end Alembic commands ###
