"""Add indicator_data table

Revision ID: 668e9c4ad38b
Revises: 350a7d6bf972
Create Date: 2023-12-07 13:00:12.518287

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '668e9c4ad38b'
down_revision = '350a7d6bf972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_solar_power', sa.Integer(), nullable=False),
    sa.Column('current_wind_power', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('solar_battery_power', sa.Integer(), nullable=False),
    sa.Column('wind_power', sa.Integer(), nullable=False),
    sa.Column('power_consumption', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_data_id'), 'equipment_data', ['id'], unique=True)
    op.create_table('indicator_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voltage_deviation', sa.Integer(), nullable=False),
    sa.Column('phase_voltage_ua', sa.Integer(), nullable=False),
    sa.Column('phase_voltage_ub', sa.Integer(), nullable=False),
    sa.Column('phase_voltage_uc', sa.Integer(), nullable=False),
    sa.Column('interphase_voltage_uab', sa.Integer(), nullable=False),
    sa.Column('interphase_voltage_uac', sa.Integer(), nullable=False),
    sa.Column('interphase_voltage_ubc', sa.Integer(), nullable=False),
    sa.Column('asymmetry_coefficient_k2u', sa.Integer(), nullable=False),
    sa.Column('asymmetry_coefficient_k0u', sa.Integer(), nullable=False),
    sa.Column('capacity_battery_pb', sa.Integer(), nullable=False),
    sa.Column('current_solar_power', sa.Integer(), nullable=False),
    sa.Column('current_wind_power', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('solar_battery_power', sa.Integer(), nullable=False),
    sa.Column('wind_power', sa.Integer(), nullable=False),
    sa.Column('power_consumption', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_data_id'), 'indicator_data', ['id'], unique=True)
    op.drop_index('ix_forecast_switch_forecast_id', table_name='forecast_switch')
    op.drop_table('forecast_switch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_switch',
    sa.Column('forecast_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('v1_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('v2_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('v3_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('v4_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('v5_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('v6_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('v7_state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('forecast_id', name='forecast_switch_pkey')
    )
    op.create_index('ix_forecast_switch_forecast_id', 'forecast_switch', ['forecast_id'], unique=False)
    op.drop_index(op.f('ix_indicator_data_id'), table_name='indicator_data')
    op.drop_table('indicator_data')
    op.drop_index(op.f('ix_equipment_data_id'), table_name='equipment_data')
    op.drop_table('equipment_data')
    # ### end Alembic commands ###
