"""Add indicator table

Revision ID: 78f004ff08b4
Revises: 602147c8dff9
Create Date: 2023-12-13 21:58:54.890420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f004ff08b4'
down_revision = '602147c8dff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator', sa.Column('input', sa.JSON(), nullable=False))
    op.add_column('indicator', sa.Column('switch', sa.JSON(), nullable=False))
    op.drop_column('indicator', 'current_solar_power')
    op.drop_column('indicator', 'power_consumption')
    op.drop_column('indicator', 'interphase_voltage_ubc')
    op.drop_column('indicator', 'asymmetry_coefficient_k2u')
    op.drop_column('indicator', 'phase_voltage_ua')
    op.drop_column('indicator', 'asymmetry_coefficient_k0u')
    op.drop_column('indicator', 'phase_voltage_uc')
    op.drop_column('indicator', 'solar_battery_power')
    op.drop_column('indicator', 'wind_power')
    op.drop_column('indicator', 'capacity_battery_pb')
    op.drop_column('indicator', 'capacity')
    op.drop_column('indicator', 'voltage_deviation')
    op.drop_column('indicator', 'current_wind_power')
    op.drop_column('indicator', 'phase_voltage_ub')
    op.drop_column('indicator', 'interphase_voltage_uac')
    op.drop_column('indicator', 'interphase_voltage_uab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator', sa.Column('interphase_voltage_uab', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('interphase_voltage_uac', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('phase_voltage_ub', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('current_wind_power', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('voltage_deviation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('capacity_battery_pb', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('wind_power', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('solar_battery_power', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('phase_voltage_uc', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('asymmetry_coefficient_k0u', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('phase_voltage_ua', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('asymmetry_coefficient_k2u', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('interphase_voltage_ubc', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('power_consumption', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('indicator', sa.Column('current_solar_power', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('indicator', 'switch')
    op.drop_column('indicator', 'input')
    # ### end Alembic commands ###
