---
name: Build

on: [push]  # yamllint disable-line rule:truthy

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          flake8 && isort --check --diff . && mypy

      - name: Test with pytest
        run: |
          pytest .
