---
name: Build

on: [push]  # yamllint disable-line rule:truthy

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    services:
      itenergy-service:
        build: .
        container_name: itenergy
        depends_on:
          - itenergy-service-postgres
        volumes:
          - ${PWD}:/app
        command: [ "uvicorn", "itenergy.app:app", "--host", "0.0.0.0", "--port", "8000" ]

      itenergy-service-postgres:
        container_name: itenergy-service-postgres
        image: postgres:14.2
        environment:
          PGHOST: itenergy-service-postgres
          PGPORT: 5432
          POSTGRES_DB: itenergy
          POSTGRES_USER: itenergy
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          flake8 && isort --check --diff . && mypy

      - name: Set env
        run: | 
          echo "PGHOST=itenergy-service-postgres" >> $GITHUB_ENV
          echo "PGPORT=5433" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $PGHOST
          echo $PGPORT

      - name: Test with pytest
        run: |
          pytest .
